import json
from pathlib import Path

class JSONASTLoader:
    """
    JSON Injection Bridge (Data Loader).
    Responsible for reading the AST JSON files generated by the Parser Agent
    and loading them into memory as a Python dictionary.
    """

    @staticmethod
    def load(filepath: str) -> dict:
        """
        Loads a JSON file containing the AST representation.
        
        Args:
            filepath (str): Path to the JSON file.
            
        Returns:
            dict: The parsed AST as a dictionary.
        """
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f"AST JSON file not found: {filepath}")
            
        with open(path, 'r', encoding='utf-8') as f:
            ast_dict = json.load(f)
            
        return ast_dict
